apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2 # Number of instances (pods) to run
  selector:
    matchLabels:
      app: my-container 
      env: blue
# everything under template is the definition of the pod that will be created.
  template:
    metadata:
      labels:
        app: my-container
        env: blue
    spec:
      containers:
        - name: web-app
          image: europe-southwest1-docker.pkg.dev/unique-poetry-470811-t2/week3/main:main
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  selector:
    app: my-container
    env: blue
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
